### ISSUE TITLE
Can't upload .wasm

### ISSUE THREAD

**Issue by triccs** [CyberHoward/cosm-rust-script#5]
I keep getting " No such file or directory (os error 2)" when trying to run a `cw-plus-script` esqe script. 

My WASM_DIR is currently pointing to the artifacts folder and I am passing in a ".wasm" file to the upload function.

I've tried a couple of different variations but same error. I understand if you don't have the time to assist.

This is the debug output:
![image](https://user-images.githubusercontent.com/105668529/190202717-6bd117cc-8553-46fc-bc37-72085041fc60.png)

**Comment by CyberHoward** [comment]
If you're providing the .wasm path then you should give it the absolute file path so on linux it would be something like `/home/cyberhoward/.../osmosis_proxy.wasm`. If you just provide the file name so "osmosis_proxy" and set the WASM_DIR in the .env file it should also work.
